### ISSUE TITLE
Please also create git tags while releasing new crate versions

### ISSUE THREAD

**Issue by Xuanwo** [tikv/pprof-rs#139]
So that users know which commits we are on.

**Comment by YangKeao** [comment]
The problem is: the only maintainer of this project @YangKeao cannot push directly. He rarely contributes to the `tikv/tikv` directly, and doesn't pay a lot attention to the community of tikv, so he doesn't know when/how/why it happened :confused: . He has tagged some commits a long time ago, but after some point in time, he cannot do it anymore.

Maybe when he is not that tired, he'd like to contact someone who knows the community rule of the tikv to help him solve the problem.

**Comment by Xuanwo** [comment]
> Maybe when he is not that tired, he'd like to contact someone who knows the community rule of the tikv to help him solve the problem.

Based on my knowledge, only tikv committers can push tags directly.

Possible solutions include as follows:

- Inviting one of the committers to take care of this project, maybe @andylokandy? They don't need to take part in the development, just need to push tags for release. I think it's not a big burden since `pprof-rs` is not heavy traffic.
- Ping one of tikv's maintainers to give you more rights on this project. Because it doesn't make sense that you are the maintainer of `pprof-rs` but don't have permission to push tags.
- Transfer this project out of tikv's umbrella if the tikv community doesn't have an interest in maintaining it.

Also, ping @tisonkun for more advice about the current situation.

---

[Databend](https://github.com/datafuselabs/databend) depends heavily on `pprof-rs` and I'm interested in maintaining `pprof-rs`, we can help maintain this project.

**Comment by Xuanwo** [comment]
I will raise this issue to tikv/community to get more ideas.

**Comment by Xuanwo** [comment]
Ping all maintainers of `tikv` for comments:

- @BusyJay 
- @andylokandy 
- @breezewish 
- @hicqu 
- @innerr 
- @nrc 
- @skyzh 
- @yiwu-arbug

**Comment by tisonkun** [comment]
@YangKeao you have `Maintain` access to this repository already.

**Comment by YangKeao** [comment]
> @YangKeao you have `Maintain` access to this repository already.

Sorry for the misleading. As I just tried, I can push a tag, but cannot push to master directly, is it expected?

I think it's fine to push the tags :laughing: . I'll tag some old releases to fix this problem.

**Comment by Xuanwo** [comment]
> As I just tried, I can push a tag (v0.9.1), but cannot push to master directly, is it expected?

I think it's expected. the `master` branch is protected and doesn't allow pushing directly.

> Then the release process would be: @YangKeao submits a PR to upgrade the version, after it's merged, he will tag the commit and push the tag.

Looks good to me!

**Comment by skyzh** [comment]
Maybe we can integrate with a GitHub Action to automatically create release (and possibly upload to crates.io?)

Some examples: https://github.com/risinglightdb/sqllogictest-rs/blob/main/.github/workflows/release.yml

**Comment by YangKeao** [comment]
> Maybe we can integrate with a GitHub Action to automatically create release (and possibly upload to crates.io?)
> 
> Some examples: https://github.com/risinglightdb/sqllogictest-rs/blob/main/.github/workflows/release.yml

Automatically publishing on crates.io is pretty cool, maybe I could add a bot as the owner of this crate, and publish the crate through bot's token :thinking: .

**Comment by Xuanwo** [comment]
Closing for addressed, thanks @YangKeao again!

And also thanks advice from @tisonkun @skyzh.
