### ISSUE TITLE
Compiling fails on FreeBSD

### ISSUE THREAD

**Issue by dveeden** [tikv/pprof-rs#151]
```
% cargo build
   Compiling pprof v0.10.0 (/usr/home/dveeden/dev/pprof-rs)
error[E0425]: cannot find function `create_pipe` in this scope
  --> src/addr_validate.rs:52:35
   |
52 |         let (read_fd, write_fd) = create_pipe()?;
   |                                   ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `addr` in this scope
   --> src/profiler.rs:280:44
    |
280 |                 if profiler.is_blocklisted(addr) {
    |                                            ^^^^ not found in this scope

error[E0308]: mismatched types
   --> src/profiler.rs:205:9
    |
205 | /         unsafe {
206 | |             #[cfg(target_os = "linux")]
207 | |             {
208 | |                 let errno = *libc::__errno_location();
...   |
215 | |             }
216 | |         }
    | |_________^ expected struct `ErrnoProtector`, found `()`

Some errors have detailed explanations: E0308, E0425.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `pprof` due to 3 previous errors
```

```
% freebsd-version 
13.0-RELEASE-p11
% cargo --version
cargo 1.63.0-nightly
```

**Comment by dveeden** [comment]
This would be a start:
```diff
diff --git a/src/profiler.rs b/src/profiler.rs
index 4bc72ad..52fcb86 100644
--- a/src/profiler.rs
+++ b/src/profiler.rs
@@ -208,6 +208,11 @@ impl ErrnoProtector {
                 let errno = *libc::__errno_location();
                 Self(errno)
             }
+            #[cfg(target_os = "freebsd")]
+            {
+                let errno = *libc::__error();
+                Self(errno)
+            }
             #[cfg(target_os = "macos")]
             {
                 let errno = *libc::__error();
```

**Comment by dveeden** [comment]
Or even better:
```diff
diff --git a/src/addr_validate.rs b/src/addr_validate.rs
index 9e9a34c..7ceafd0 100644
--- a/src/addr_validate.rs
+++ b/src/addr_validate.rs
@@ -19,7 +19,7 @@ fn create_pipe() -> nix::Result<(i32, i32)> {
 }
 
 #[inline]
-#[cfg(target_os = "macos")]
+#[cfg(any(target_os = "macos", target_os = "freebsd"))]
 fn create_pipe() -> nix::Result<(i32, i32)> {
     use nix::fcntl::{fcntl, FcntlArg, FdFlag, OFlag};
     use nix::unistd::pipe;
diff --git a/src/profiler.rs b/src/profiler.rs
index 4bc72ad..d89c164 100644
--- a/src/profiler.rs
+++ b/src/profiler.rs
@@ -208,7 +208,7 @@ impl ErrnoProtector {
                 let errno = *libc::__errno_location();
                 Self(errno)
             }
-            #[cfg(target_os = "macos")]
+            #[cfg(any(target_os = "macos", target_os = "freebsd"))]
             {
                 let errno = *libc::__error();
                 Self(errno)
```

**Comment by YangKeao** [comment]
Good! https://github.com/tikv/pprof-rs/pull/150 is working on separating multiple implementations on different platforms. It would be better to take *bsd into consideration https://doc.rust-lang.org/reference/conditional-compilation.html#target_os .

**Comment by dveeden** [comment]
@YangKeao do you think it still makes sense to do this as part of #150 or should we consider doing something like my suggestion?

**Comment by YangKeao** [comment]
> Or even better:
> 
> ```diff
> diff --git a/src/addr_validate.rs b/src/addr_validate.rs
> index 9e9a34c..7ceafd0 100644
> --- a/src/addr_validate.rs
> +++ b/src/addr_validate.rs
> @@ -19,7 +19,7 @@ fn create_pipe() -> nix::Result<(i32, i32)> {
>  }
>  
>  #[inline]
> -#[cfg(target_os = "macos")]
> +#[cfg(any(target_os = "macos", target_os = "freebsd"))]
>  fn create_pipe() -> nix::Result<(i32, i32)> {
>      use nix::fcntl::{fcntl, FcntlArg, FdFlag, OFlag};
>      use nix::unistd::pipe;
> diff --git a/src/profiler.rs b/src/profiler.rs
> index 4bc72ad..d89c164 100644
> --- a/src/profiler.rs
> +++ b/src/profiler.rs
> @@ -208,7 +208,7 @@ impl ErrnoProtector {
>                  let errno = *libc::__errno_location();
>                  Self(errno)
>              }
> -            #[cfg(target_os = "macos")]
> +            #[cfg(any(target_os = "macos", target_os = "freebsd"))]
>              {
>                  let errno = *libc::__error();
>                  Self(errno)
> ```

Thank you. I'll test this patch (and add some other modification, if needed) on freebsd tonight. Let's make `pprof-rs` compile on freebsd :beers:.
