### ISSUE TITLE
support for criterion 0.4

### ISSUE THREAD

**Issue by PSeitz** [tikv/pprof-rs#164]
criterion 0.4 has recently been released. The `Profiler` trait changed and is not compatible currently with `pprof`.

```
error[E0277]: the trait bound `PProfProfiler<'_, '_>: Profiler` is not satisfied
   --> benches/index-bench.rs:118:49
    |
118 |     config = Criterion::default().with_profiler(PProfProfiler::new(100, Output::Flamegraph(None)));
    |                                   ------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Profiler` is not implemented for `PProfProfiler<'_, '_>`
    |                                   |
    |                                   required by a bound introduced by this call
    |
    = help: the trait `Profiler` is implemented for `ExternalProfiler`
note: required by a bound in `Criterion::<M>::with_profiler`
   --> /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.4.0/src/lib.rs:462:29
    |
462 |     pub fn with_profiler<P: Profiler + 'static>(self, p: P) -> Criterion<M> {
    |                             ^^^^^^^^ required by this bound in `Criterion::<M>::with_profiler`
```

**Comment by tversteeg** [comment]
There's #163 for this.

**Comment by PSeitz** [comment]
Cool, it's been merged.
@YangKeao Can you release a new version?

**Comment by TheLostLambda** [comment]
Seconding this! Would be nice to have a version released with this PR integrated!

**Comment by Fomalhauthmj** [comment]
Before the newer release,we can use 
`pprof = { git = "https://github.com/tikv/pprof-rs", features = [
    "flamegraph",
    "criterion",
] } 
`in `Cargo.toml`  temporarily.

**Comment by aminya** [comment]
> Before the newer release,we can use
> `pprof = { git = "https://github.com/tikv/pprof-rs", features = [ "flamegraph", "criterion", ] }` in Cargo.toml temporarily.

Thanks. Yeah, the master branch works with Criterion 0.4. I would recommend a locked `rev` just for reproducibility:
```toml
[target.'cfg(unix)'.dev-dependencies]
# pprof = "0.10.1"
pprof = { git = "https://github.com/tikv/pprof-rs", rev="a280c9e71f", features = ["flamegraph", "criterion"] }
```

**Comment by breezewish** [comment]
0.11.0 is released, which contains the change 🎉
