### ISSUE TITLE
Tests fail with latest rustc.

### ISSUE THREAD

**Issue by plugwash** [tikv/pprof-rs#250]
Related to https://github.com/tikv/pprof-rs/issues/232

The "validate" function tries to write data to a pipe from a pointer of unknown validity.

Unfortunately, the function tries to convert the possibly-invalid pointer to a slice, this is unsound and with recent rustc leads to the testsuite panicing

    thread 'addr_validate::test::failed_validate' panicked at library/core/src/panicking.rs:220:5:
    unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`

In Debian I fixed this by using libc::write directly instead of nix::unistd::write

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/pprof/debian/patches/use-libc-write-for-validation.patch

**Comment by shinmao** [comment]
hi @plugwash , could you provide more details about how you trigger this panic on `addr_validate::test::failed_validate` or the backtrace?

**Comment by shinmao** [comment]
@plugwash , do you have any other case that could trigger the panic on `validate`? As far as I know, even though the test suite panic; however, no one will use it like this way (pass a constant address), isn't it?
https://github.com/tikv/pprof-rs/blob/4939f73f0cc2e8d92e3c2c50c9d02d6d4c205a86/src/addr_validate.rs#L126

**Comment by plugwash** [comment]
No, I simply ran into the test failure while working on Debian rust packaging.

**Comment by shinmao** [comment]
Yes. I think `validate(-1_i32 as usize as *const libc::c_void)` is expected to return false here; however, it panic due to precondition check in `from_raw_parts`.

**Comment by vorporeal** [comment]
Just dug into this a little and found that adding an `if addr.is_null() { return false; }` check at the top of the `validate()` function fixes the problem for me.

Wish the maintainers of this repo were responsive; seems like it might be an easy fix. :(

**Comment by mati865** [comment]
Just switch to [pprof2](https://crates.io/crates/pprof2) maintained by Embark Studios.
