### ISSUE TITLE
Question: Concurrency support

### ISSUE THREAD

**Issue by xd009642** [tikv/pprof-rs#26]
If I was to use this to profile a method in a server would I be able to create a profile report for each request event ones occurring concurrently? Or does it use anything like signals that could interfere with this use case?

**Comment by YangKeao** [comment]
Yes. It uses `setitimer` to send `SIGPROF` to itself periodically, so it cannot run concurrently.

**Comment by xd009642** [comment]
okay thanks for helping :+1:
