### ISSUE TITLE
RUSTSEC-2019-0031: spin is no longer actively maintained

### ISSUE THREAD

**Issue by extrawurst** [tikv/pprof-rs#31]
> spin is no longer actively maintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `spin`                      |
| Version             | `0.5.2`                   |
| URL                 | [https://github.com/mvdnes/spin-rs/commit/7516c80](https://github.com/mvdnes/spin-rs/commit/7516c80) |
| Date                | 2019-11-21                         |

The author of the `spin` crate does not have time or interest to maintain it.

Consider the following alternatives (both of which support `no_std`):

- [`conquer-once`](https://github.com/oliver-giersch/conquer-once)
- [`lock_api`](https://crates.io/crates/lock_api) (a subproject of `parking_lot`)
  - [`spinning_top`](https://github.com/rust-osdev/spinning_top) spinlock crate built on `lock_api`

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2019-0031.html) for additional details.

I came across this issue in gitui: https://github.com/extrawurst/gitui/issues/172

**Comment by YangKeao** [comment]
Fixed by #29 

Thanks for @koushiro

**Comment by extrawurst** [comment]
@YangKeao oh did no see the PR! cool! can you tag a release? ;)

**Comment by extrawurst** [comment]
@YangKeao sorry to bother you with this again. would love to upgrade to a version of pprof without the sec warning of `spin` 🙏 can has a release? ❤️

**Comment by YangKeao** [comment]
@extrawurst Sorry for wasting you time :cry: .  `v0.3.17` has been released with `parking_lot`.

Thanks for your reminder :beers:

**Comment by extrawurst** [comment]
no worries! thanks for this great crate ❤️
