### ISSUE TITLE
Can't see full method names in flamegraph

### ISSUE THREAD

**Issue by john01dav** [tikv/pprof-rs#38]
In order to make sense of the kind of data that a profiler produces, some sort of visualization such as a flamegraph is essentially mandatory. Yet, when I generate a flamegraph from this tool, all the method names state with the module path, which makes seeing which method it is impossible, which is blocking me from accessing any useful data.

**Comment by noahols** [comment]
I just realized the flamegraph contains javascript.
You can open it in a browser and click on any trace to zoom in on it.
This is most likely better than changing the flamegraph options manually.
