### ISSUE TITLE
pprof 0.3.21 has breaking changes

### ISSUE THREAD

**Issue by qwandor** [tikv/pprof-rs#48]
As per https://github.com/bytebeamio/rumqtt/issues/213, the latest version of pprof appears to have breaking changes. I suggest that it be yanked and re-released as 0.4.0.

**Comment by qwandor** [comment]
It looks like the issue is the update of the `prost` dependency from 0.6 to 0.7. As it forms part of the public API of `pprof`, `pprof` needs a major version bump whenever the major version of `prost` is changed.

**Comment by YangKeao** [comment]
Sorry, my mistake :crying_cat_face: . I have yanked it and will publish a `0.4.0` version after several hours. :beers:

**Comment by YangKeao** [comment]
This problem has been fixed and a `0.4.0` version has been released :beers:
