### ISSUE TITLE
Cannot work with rust 2021-01-24

### ISSUE THREAD

**Issue by YangKeao** [tikv/pprof-rs#57]
After https://github.com/rust-lang/rust/pull/77885 merged, the DWARF information of `probe-stack` parts of codes are wrong. When the signal hits `probe-stack` parts of codes, `_Unwind_Backtrace` will cause a Segmentation Fault.

I have filed an issue for rust https://github.com/rust-lang/rust/issues/83139

**Comment by YangKeao** [comment]
The related PR has been merged https://github.com/rust-lang/rust/pull/83412 14 hours ago, so I can test it today or tomorrow.

**Comment by Xuanwo** [comment]
Already fixed, closing.
