### ISSUE TITLE
Report does not implement Display

### ISSUE THREAD

**Issue by shepmaster** [tikv/pprof-rs#60]
https://github.com/tikv/pprof-rs/blob/6e67b561f2cd86657d73ee1ab1caa4f69899c517/README.md#L26

This was apparently removed in https://github.com/tikv/pprof-rs/commit/e870c110d233dc2a7a686958db2d02ee4a511d3e

**Comment by YangKeao** [comment]
Oh! It's a shame.

I will add a `Display` to it and add a `semver` CI check to avoid similar problem :man_facepalming: .

**Comment by YangKeao** [comment]
Fixed in `v0.3.22`
