### ISSUE TITLE
Not building on Mac?

### ISSUE THREAD

**Issue by nrc** [tikv/pprof-rs#7]
When building TiKV, the build fails in pprof because it cannot find `libc::pthread_getname_np`. This function only seems to be availble on Linux: https://github.com/rust-lang/libc/search?q=pthread_getname_np&unscoped_q=pthread_getname_np

**Comment by YangKeao** [comment]
Yes. I haven't found a way to get thread name on mac. Do you have any suggestions? (As rust std use a thread local RefCell to store thread related information, I cannot use it safely in signal handler function )

If I cannot find any better way to get thread name on mac, I have to use thread id as a replacement.

**Comment by YangKeao** [comment]
However,  `pthread_getname_np` is available in `pthread.h` in mac. I will try to use it. (Maybe it should be added into `rust-lang/libc`)

```c
/*SPI to set and get pthread name*/
__API_AVAILABLE(macos(10.6), ios(3.2))
int	pthread_getname_np(pthread_t,char*,size_t);

__API_AVAILABLE(macos(10.6), ios(3.2))
int	pthread_setname_np(const char*);
```

**Comment by YangKeao** [comment]
A [PR](https://github.com/rust-lang/libc/pull/1599) has been submitted for `libc` to include this function.

**Comment by YangKeao** [comment]
Fixed now.
